<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NotificationService.Infrastructure\NotificationService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
