// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260927130019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<int>("FailedDispatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_dispatch_count");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Content", "NotificationService.Domain.Notifications.Notification.Content#NotificationContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("body");

                            b1.Property<string>("Subject")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Recipient", "NotificationService.Domain.Notifications.Notification.Recipient#Recipient", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("recipient_address");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("channel");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_idempotency_key");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_notifications_due")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Notifications.Notification", b =>
                {
                    b.OwnsMany("NotificationService.Domain.Notifications.DeliveryAttempt", "DeliveryAttempts", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<DateTimeOffset>("AttemptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("attempted_at");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("failure_reason");

                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid")
                                .HasColumnName("notification_id");

                            b1.Property<string>("Outcome")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("outcome");

                            b1.Property<string>("ProviderMessageId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider_message_id");

                            b1.Property<string>("ProviderName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("provider_name");

                            b1.HasKey("Id");

                            b1.HasIndex("NotificationId");

                            b1.ToTable("delivery_attempts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("DeliveryAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
